### ISSUE TITLE
Also create for other software projects

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#1]
To provide dev environments like for example:
- PHP (general)
- JTL Shop5
- Wordpress

**Comment by joshsedl** [comment]
Done for JTL Shop 5!

**Comment by joshsedl** [comment]
@JPustkuchen do you think a dev environment for wordpress is still necessary?

**Comment by thomasfrobieter** [comment]
No, its not!
