### ISSUE TITLE
Add .eslintignore for only linting custom modules and themes

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#103]
For some reason
~~~
*
!web/modules/custom
...
~~~
does not work, even if it should, see https://eslint.org/docs/user-guide/configuring/ignoring-code#the-eslintignore-file

**Comment by JPustkuchen** [comment]
Does it perhaps need a / in the end?

~~~
!web/modules/custom/
~~~

Just an idea.

**Comment by joshsedl** [comment]
We are using the Drupal eslintignore now, see https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/b37c8897933b4cad80c2e56fc694caad7d3fb2f6
