### ISSUE TITLE
Create "ddev-info" command, which prints out all available commands

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#105]
See title.

**Comment by JPustkuchen** [comment]
We definitely need something like this, BUT:

Which commands do you mean? Could you give an example of the expected results?

Isn't this something which ddev should solve and perhaps already does with
`ddev`
`ddev --help`

or something like that?

If I get this right, this isn't a task at our level!

**Comment by joshsedl** [comment]
Oh, my bad yea ddev does that already with "ddev --help" 👍
