### ISSUE TITLE
Add configuration_inspector to our preinstalled dev modules

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#108]
https://www.drupal.org/project/config_inspector is a super helpful development tool to find and fix configuration issues in development!

It also provides drush commands, so if it speeds up our development, we could add a comand wrapper to show all configuration errors?
https://git.drupalcode.org/project/config_inspector/-/blob/2.0.x/src/Commands/InspectorCommands.php

Please add it to our preinstalled dev modules stack and let's use it in the future as part of our QA! :)

**Comment by joshsedl** [comment]
Fixed in https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/dcf81bfad1d5e20c00699266023262d1da4b04ac
