### ISSUE TITLE
Activate Error Logging on initiation

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#26]

**Comment by joshsedl** [comment]
Done

**Comment by JPustkuchen** [comment]
@joshsedl for the future pleasy reference the related issues in your commit message to make the changes visible in the issue :)

If there are issues later on, that helps a lot to make things more transparent.

**Comment by joshsedl** [comment]
@JPustkuchen will do so!
