### ISSUE TITLE
ddev drowl-init throws RuntimeException

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#48]
Taking the steps from the module page and running ddev drowl-init leads to

> [RuntimeException] extra.patches.drupal/core is not defined.  

directly after

> [success] Successfully enabled: admin_toolbar, admin_toolbar_tools, admin_toolbar_search, examples, stage_file_proxy, devel, devel_debug_log, devel_php, backup_migrate, serialization

**Comment by joshsedl** [comment]
Threw out extra.patches.drupal/core  because it is not possible to create a config without value

**Comment by JPustkuchen** [comment]
You can't do it this way, I guess. Then we need a different concept for composer.json files per environment.
We need this and other parts for Drupal Development Environments.

**Comment by joshsedl** [comment]
closed this prematurely, created a path variable
