### ISSUE TITLE
VSCode: Drupal custom file types not recognized at startup

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#49]
With drowl-init (Drupal projects) we should ensure Drupal file types are recognized and mapped correctly in VSCode.

![grafik](https://user-images.githubusercontent.com/637807/141730222-3839f91d-8dbf-4a2b-a797-36e47b901cf4.png)

**Comment by JPustkuchen** [comment]
Installing this plugin might be the most simple solution: https://marketplace.visualstudio.com/items?itemName=marcostazi.VS-code-drupal

Otherwise the types should be added to the VSCode settings when using Drupal.

**Comment by joshsedl** [comment]
The types are already set in the VSCode settings, I don't know why this happens, but you can fix this Problem simply by reloading the page via "F1-> Developer:Reload Window"

**Comment by joshsedl** [comment]
Closing this, as the config is loaded correctly on startup now and therefore Drupal files are recognized, even without needing to reload the page.
