### ISSUE TITLE
Change permission for default folder, so settings.php can be rewritten

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#54]

**Comment by joshsedl** [comment]
set the permission to 754

**Comment by JPustkuchen** [comment]
Please use 755 by default. Typically, we should always use

755 for folders
644 for files.

as standard. FYI: Drupal typically makes the settings files readonly on cron run, thats expected behaviour and ok.

**Comment by joshsedl** [comment]
Done: 
#f721d3f4b37cba059e14257d23640ebec12ff215

https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/f721d3f4b37cba059e14257d23640ebec12ff215
