### ISSUE TITLE
Setup for a DDEV Vue environment 

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#57]
Maybe we can discuss here what tools/settings we would need for a DDEV Vue Development environment :)

**Comment by joshsedl** [comment]
Gulp custom ddev command:
https://github.com/drud/ddev-contrib/blob/master/custom-commands/gulp/gulp

Vue tests using Nightwatch/Jest:
https://hashnode.com/post/how-to-test-your-vue-project-with-jest-and-nightwatch-cjskmturk00665ss1gauawb84

**Comment by JPustkuchen** [comment]
I guess as this is ... -drupal9- template that should definitely be a separate project then. Perhaps ddev isn't made for this, let's postpone this until we need it.

**Comment by joshsedl** [comment]
https://github.com/microsoft/vscode-dev-containers/issues/960

**Comment by joshsedl** [comment]
Closing this, since it has nothing to-do with this current repository and ddev should not be used to generate a vue software stack. Instead, we should use Nuxt and co.

But the VSCode dev-container vuw template would be an interesting solution, maybe we can somehow implement it in our future vue stack, making notes internally about this..
