### ISSUE TITLE
Create additional directories (only in drowl-init-from-existing)

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#60]
mkdir assets files log scipts tmp

**Comment by JPustkuchen** [comment]
I think we only need this for drowl-init-from-existing. Perhaps also ask for it ... 

> Would you like to create the drupal best-practice folder structure (assets, files, log, scripts, tmp) in the project root directory?

 Or something like that.

**Comment by joshsedl** [comment]
Done
https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/aced430e5c16a2b9d267aae878e5b3d7bf3103a6
