### ISSUE TITLE
On drowl-init (&-from...) first check if a .git folder exists and ask to delete it

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#62]
We should ensure the .git repository from this repo is deleted before we initialize a project.
So check if a .git folder exists when running drowl-init[-...] and ask if the repository should be deleted (which is typically recommended to not commit into ddev-vscode-devcontainer-drupal9-template!)

**Comment by joshsedl** [comment]
Done:

https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/b83b8a1bb01d9089168c476a341d2c336ba77302
