### ISSUE TITLE
Add php-cs-fixer support, when it supports @Drupal and @DrupalPractice rulesets

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#71]
The current php-cs-fixer does not work properly

**Comment by joshsedl** [comment]
POSTPONED on: 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6083

**Comment by joshsedl** [comment]
When fixed, require `friendsofphp/php-cs-fixer` on drowl-init and drowl-init-from-existing.

And change this to .sh nad add it under commands/web:
[phpfix.md](https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/files/7596273/phpfix.md)
d

**Comment by joshsedl** [comment]
phpcbf should be enough in the meantime

**Comment by joshsedl** [comment]
I am not sure why we would use "php-cs-fixer" over our currently flawless working phpcs + phpcbf setup. I know php-cs-fixer was created by symfony, but I see no point using it over phpcs / phpcbf.

@JPustkuchen what do you think? Can I close this issue? 

Note: We are currently using phpcs as our VSCode Linter and phpcbf as our standard VSCode formatter! Additionally we also have phpcbf and phpcs ddev commands specified.

**Comment by JPustkuchen** [comment]
@joshsedl if we have everything we need working and php-cs-fixer wouldn't put in much benefit, we should close this. 👍

**Comment by joshsedl** [comment]
Closing this then.
