### ISSUE TITLE
PHPCBF VSCode Extension "valeryanm.vscode-phpsab" does not work properly

### ISSUE THREAD

**Issue by joshsedl** [webksde/ddev-vscode-devcontainer-drupal9-template#72]
Use `ddev phpcbf path/to/fix` in the meantime

**Comment by joshsedl** [comment]
Eventually kill this whole feature, since the custom "ddev phpcbf path/to/fix" is WAY better anyways (Folder support and shows remaining manual fixes)

**Comment by JPustkuchen** [comment]
Nope :P 

But postpone it until any of the VSCode extensions work ;)

**Comment by joshsedl** [comment]
I am not sure what exactly "does not work properly" for the extension, and I have not specified the problem in this thread. We are currently using "valeryanm.vscode-phpsab" as our default formatter, and it works just fine!

So I am closing this, since the extension is working as intended.

PS: Use "Shift+Alt+F" to format the current document using phpcbf.
