### ISSUE TITLE
Suggest 'ddev drush config-set stage_file_proxy.settings origin XXX' command after using drowl-init-from-existing

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#78]
See https://www.drupal.org/project/stage_file_proxy

> Simple install and configuration for Drupal 8
> 
> It is recommended to use Composer to install the module and you can use Drush to configure it:
> 
> composer require drupal/stage_file_proxy
> drush en stage_file_proxy
> drush config-set stage_file_proxy.settings origin "https://www.example.com"
> 
> Of course, replace example.com with your live site.

As stage_file_proxy is typically used for drowl-init-from-existing it would be nice to suggest to the user to run
`ddev drush config-set stage_file_proxy.settings origin XXX`
after drowl-init-from-existing finished

A simple message would be enough so the user doesn't have to look things up and won't forget the "ddev" prefix prior to the command.

**Comment by joshsedl** [comment]
Implemented but not tested yet, see https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/b16e49bc3f1bf93bd96058b1bf9293a2e61ebd07

**Comment by joshsedl** [comment]
Fixed and tested! https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/commit/79abcbb7bb53685badc816751dd8e256501cc85d
