### ISSUE TITLE
Do not set rebuild_access=true in local.settings.php

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#79]
admin/reports/status says:
> Zugriff neu aufbauen
> Aktiviert
> Die Einstellung rebuild_access, in der Datei settings.php. ist aktiviert. Es wird empfohlen, diese Einstellung zu deaktivieren, wenn Sie keinen Neuaufbau der Drupal-Caches durchführen.

And as we did never require using this so far in our development, I guess it should not need to set to true by default. Or was there any specific reason / problem?

**Comment by JPustkuchen** [comment]
Background: That setting controls if access records are rebuilt on each request. As we typically don't change access records frequently nor use the environment to write such modules, it's an edge case which is better not to implement by default.

If someone needs it for such a case (which has never been the case in company history), he / she should know about that setting or rebuild permissions manually.

**Comment by JPustkuchen** [comment]
Created a pull request for this: https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/pull/84

**Comment by joshsedl** [comment]
Sounds good!

**Comment by joshsedl** [comment]
Merged.
