### ISSUE TITLE
.ddev/.homeadditions vs ddev/homeadditions

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#83]
The .ddev directory contains two folders that seem similar? Please check, if this is still both required or perhaps changed at ddev?

![grafik](https://user-images.githubusercontent.com/637807/151773714-294217da-25e7-460f-9bab-5beb28be0ab1.png)

**Comment by joshsedl** [comment]
This seems to be a bug related to ddev, I created an issue at drud/ddev: https://github.com/drud/ddev/issues/3571
