### ISSUE TITLE
ddev code: VSCode shows error: felixfbecker.php-debug (not found in marketplace)

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#85]
> The 1 extension(s) below, in workspace recommendations have issues: felixfbecker.php-debug (not found in marketplace)

![grafik](https://user-images.githubusercontent.com/637807/151785469-012d2ca5-2f0e-4c75-9068-135709744724.png)

Directly after starting VSCode with `ddev code`

**Comment by JPustkuchen** [comment]
Is this perhaps simply the new name: https://marketplace.visualstudio.com/items?itemName=xdebug.php-debug
?

**Comment by JPustkuchen** [comment]
Created a pull request: https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/pull/87

**Comment by joshsedl** [comment]
Done ;)
