### ISSUE TITLE
Try .code-workspace file for extension recommendation?

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#86]
Just saw

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_extension-recommendations

Perhaps that file works better for installing the recommendations?

**Comment by joshsedl** [comment]
"You can also provide GLOBAL Workspace extension recommendations by adding them to your .code-workspace" I don't think we would like to set the recommendations for every single workspace, we only want the recommendations for the "ddev devcontainer drupal" workspace.

In the future we won't recommend the extensions any more anyway, but rather provide an extensions and settings file which can be used as a "devcontainer.json" by the attached container. With this setup the extensions will be automatically installed. For reference, you can have a look at https://github.com/microsoft/vscode-remote-release/issues/5944#issuecomment-989740529 but this feature is currently postponed on https://github.com/microsoft/vscode-remote-release/issues/5278
