### ISSUE TITLE
ddev drowl-init throws error [Seld\JsonLint\ParsingException]   "" does not contain valid JSON

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#92]
![grafik](https://user-images.githubusercontent.com/637807/159469836-6c696211-a24c-499a-bd09-40418773405a.png)

```
[Seld\JsonLint\ParsingException]
  "" does not contain valid JSON
  Parse error on line 1:
  '{"INSERT WHAT IT DO
  ^
  Invalid string, it appears you used single quotes instead of double quotes
```

On first initialization in a fresh project. Using ddev 1.19.1

**Comment by JPustkuchen** [comment]
Looks like this line fails:

`ddev composer config --json extra.patches.package-mantainer/package "'{\"INSERT WHAT IT DOES\": \"PATH TO PATCH\"}'"`
https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/blob/d5e44e8a6e8ffde4d4226b635d4d9b5ae3391c1a/.ddev/commands/host/drowl-init.sh#L70

**Comment by JPustkuchen** [comment]
I'll try to fix it.

**Comment by JPustkuchen** [comment]
Fixed in https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/pull/93

**Comment by joshsedl** [comment]
Thanks @JPustkuchen! :)

**Comment by joshsedl** [comment]
Note, that this change will make ddev >=1.19.1 required!

**Comment by JPustkuchen** [comment]
Thanks @joshsedl - but I think that's OK... please notify the team to upgrade. I used brew for that.
